title: "Eddy Diomande"
logo: "https://raw.githubusercontent.com/mik129/MIK/main/img/Capture%20d'%C3%A9cran%202026-01-20%20123646.png"
description: "Étudiant en Cybersécurité – Linux, Réseau, Sécurité"
show_downloads: false
theme: jekyll-theme-minimal
